### ISSUE TITLE
Make DataPollster and Schedule Singletons

### ISSUE THREAD

**Issue by tjsg1992** [360Group3/UrbanParksProject#31]
DataPollster and Schedule are creating excess dependencies, as Main must call ParkManager.initialize() to assign them. If we make DataPollster and Schedule Singletons, we would remove the dependencies between Main and the User classes.

**Comment by lethargilistic** [comment]
Taylor did this [here](https://github.com/360Group3/UrbanParksProject/commit/0a4d99eb8ed1580a6db1f99bf5dcf96ec2fa8243).
