### ISSUE TITLE
Rename Main and MainUI to something else

### ISSUE THREAD

**Issue by tjsg1992** [360Group3/UrbanParksProject#32]
This is just to ease confusion, so think of a more fitting name for Main and MainGUI (Login and LoginGUI?) and rename them.

**Comment by lethargilistic** [comment]
I do like Login and LoginGUI, for the record. The only problem with that would be that the name wouldn't make it obvious that it's where our main method is. Because of that, I think that a separate Runner class would still be a good idea.

**Comment by lethargilistic** [comment]
We decided to create the separate Runner class, which is now Issue #50.

**Comment by reidobandedo** [comment]
The 2 new classes are named Login and LoginUI.
