### ISSUE TITLE
Change Schedule methods so that they throw Exceptions

### ISSUE THREAD

**Issue by tjsg1992** [360Group3/UrbanParksProject#36]
Right now, Schedule returns null even if there are multiple things that could go wrong. For instance, if a Volunteer tries to sign up for a job, the job may be full, or it may be in the past, or it may be on the same day of another job that they're signed up for.

Right now, Schedule just returns null in these instances, which doesn't tell Volunteer what went wrong. Instead, Schedule should throw and exception that Volunteer can catch, and then react to how it wants.

**Comment by lethargilistic** [comment]
We did this a while ago.
