### ISSUE TITLE
Refactor DataPollster

### ISSUE THREAD

**Issue by tjsg1992** [360Group3/UrbanParksProject#49]
DataPollster is kind of a mess right now. Let's get it cleaned up by removing unnecessary comment blocks, organizing methods, and optimizing where we can.

**Comment by lethargilistic** [comment]
Taylor handled this [here](https://github.com/360Group3/UrbanParksProject/commit/c5fc040a89a0529c3c77674782e25bee4d74c5a7#diff-c383ddd1700a0a59e89659e0554f5152).
