### ISSUE TITLE
Allowing users more than one input chance

### ISSUE THREAD

**Issue by lethargilistic** [360Group3/UrbanParksProject#68]
In our code, when we ask a user for input, we only use an if to do it. This gives them one chance, then says "sorry!" We could use a while here to give them more than one chance. I'll mark these places in our program.

**Comment by lethargilistic** [comment]
* In [AdministratorUI](https://github.com/360Group3/UrbanParksProject/blob/master/UrbanParksProject/src/view/AdministratorUI.java#L165)
* In [MainUI](https://github.com/360Group3/UrbanParksProject/blob/master/UrbanParksProject/src/view/MainUI.java#L126)
* In [VolunteerUI](https://github.com/360Group3/UrbanParksProject/blob/master/UrbanParksProject/src/view/VolunteerUI.java#L315)

**Comment by tjsg1992** [comment]
The while loop would have to be within the methods calling getUserString(). Putting it within getUserString() would cause a lot of problems.
